### ISSUE TITLE
[Koin 1.0] - Roadmap

### ISSUE THREAD

**Issue by arnaudgiuliani** [InsertKoinIO/koin#114]
Hello all,

here is the backlog for the next release `1.0.0`. Feature proposals, bugfixes & enhancement can be proposed by external contributors as usual. For some issue, we can need feedback or contributors.

Project organization:
- [x] Update repository with Code of conduct & Contributing documents
- [x] Bring back samples projects into examples folder (Android, Core)

Getting started & developer guides:
- [x] Getting started koin-core
- [x] Getting started koin-android
- [x] Getting started koin-android-viewmodel
- [x] Developer guide - Android MVP
- [ ] Developer guide - Android MVVM

Documentation:
- [x] Prepare adoc html/pdf generation with gradle
- [x] Migrate all documentation to adoc format - each project must have its doc folder with its adoc files
- [x] help prepare docs for web integration

Project Building:
- [x] Add adoc documentation for pdf/html generation
- [x] Continuous build - CI chain with tests & lints (on cloud)

Features proposals & updates:
- [x] DSL renaming for applicationContext & context keywords -> make API and naming clearer 
- [x] Better scope/visibility/context management (see DSL renaming above)
- [x] DSL - provide keyword is now internal (remove deprecated) 

- [x] Android scopedWith
- [x] koin-android repackaging - new modules
- [x] Explicide definition override 
- [x] Eager loading for module (create bean instances at startup)
- [x] Java availability tools - see (https://github.com/Ekito/koin/pull/106)
- [x] library updates (kotlin, android, arch components, spark kotlin, ktor)

+ all `type:feature-proposal` or `type:enhancement`issues

BugFixes: all issues tagged with `1.0.0`

Contributor projects: We are thinking about projects that are not directly maintained by the Koin team
